# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/carlos/work/falco-config/cross_compile/src/falco;/home/carlos/work/falco-config/cross_compile/build_ebpf/falco")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Unspecified;falco;falco-driver;libs-deps;scap;sinsp")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/scripts/debian/postinst;/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/scripts/debian/prerm;/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/scripts/debian/postrm;/home/carlos/work/falco-config/cross_compile/src/falco/cmake/cpack/debian/conffiles")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://www.falco.org")
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_SUGGESTS "dkms (>= 2.1.0.0)")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "falco built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/home/carlos/work/falco-config/cross_compile/src/falco;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/home/carlos/work/falco-config/cross_compile/install_ebpf")
set(CPACK_MODULE_PATH "/home/carlos/work/falco-config/cross_compile/src/falco/cmake/modules;/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/cmake/modules")
set(CPACK_NSIS_DISPLAY_NAME "falco 0.44.0-0+865284d")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "falco 0.44.0-0+865284d")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/opt/cross-compile/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu//bin/aarch64-none-linux-gnu-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/opt/cross-compile/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu//bin/aarch64-none-linux-gnu-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "cncf-falco-dev@lists.cncf.io")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/carlos/work/falco-config/cross_compile/src/falco/scripts/description.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Falco - Container Native Runtime Security")
set(CPACK_PACKAGE_FILE_NAME "falco-0.44.0-0+865284d-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "falco 0.44.0-0+865284d")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "falco 0.44.0-0+865284d")
set(CPACK_PACKAGE_NAME "falco")
set(CPACK_PACKAGE_RELOCATABLE "false")
set(CPACK_PACKAGE_VENDOR "Cloud Native Computing Foundation (CNCF) cncf.io.")
set(CPACK_PACKAGE_VERSION "0.44.0-0+865284d")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "44")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PROJECT_CONFIG_FILE "/home/carlos/work/falco-config/cross_compile/src/falco/cmake/cpack/CMakeCPackOptions.cmake")
set(CPACK_READELF_EXECUTABLE "/opt/cross-compile/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.28/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/usr/src;/usr/share/man;/usr/share/man/man8;/etc;/usr;/usr/bin;/usr/share")
set(CPACK_RPM_PACKAGE_ARCHITECTURE, "amd64")
set(CPACK_RPM_PACKAGE_LICENSE "Apache v2.0")
set(CPACK_RPM_PACKAGE_RELOCATABLE "OFF")
set(CPACK_RPM_PACKAGE_REQUIRES "systemd")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_RPM_PACKAGE_SUGGESTS "dkms, kernel-devel")
set(CPACK_RPM_PACKAGE_URL "https://www.falco.org")
set(CPACK_RPM_PACKAGE_VERSION "0.44.0-0+865284d")
set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/scripts/rpm/postinstall")
set(CPACK_RPM_POST_UNINSTALL_SCRIPT_FILE "/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/scripts/rpm/postuninstall")
set(CPACK_RPM_PRE_UNINSTALL_SCRIPT_FILE "/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/scripts/rpm/preuninstall")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/carlos/work/falco-config/cross_compile/src/falco;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "falco-0.44.0-0+865284d-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/carlos/work/falco-config/cross_compile/build_ebpf/falco/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
